import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import PrivyProvider from "@/components/privy-provider";
import SideBar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <PrivyProvider>
          <div className="flex">
            {/* sidebar logic: if loged in then show other wise display none */}
            <SideBar />
            <div className="flex-1">{children}</div>
          </div>
        </PrivyProvider>
      </body>
    </html>
  );
}
